# Generated by Django 3.2.2 on 2021-05-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=2)),
                ('apellido_m', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('rut_sin_dv', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.BooleanField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.BooleanField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.BooleanField(primary_key=True, serialize=False)),
                ('hora_ini', models.DateField()),
                ('hora_ter', models.DateField()),
            ],
            options={
                'db_table': 'turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id_vale', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('n_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVale',
            fields=[
                ('cantidad', models.IntegerField()),
                ('vale_id_vale', models.OneToOneField(db_column='vale_id_vale', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.vale')),
            ],
            options={
                'db_table': 'detalle_vale',
                'managed': False,
            },
        ),
    ]
