# Generated by Django 3.2.4 on 2021-06-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210608_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='clave',
        ),
    ]
